backend:
  name: github
  repo: efortney28/cam-construction

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "work"
    label: "Work Entry"
    folder: "content/work"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Completion Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Images", name: "images", widget: "image"}
  - name: "testamonial"
    identifier_field: name
    label: "Testamonial"
    folder: "content/testamonials"
    create: true
    fields:
      - {label: "Customer Name", name: "name", widget: "string"}
      - {label: "Customer Location", name: "location", widget: "string"}
      - {label: "Customer Comments", name: "comments", widget: "string"}